name: Deploy Pages | beta

on:
  push:
    branches:
      - beta
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: write
    uses: ./.github/workflows/deploy-shared.yml
    with:
      target_env: beta
