name: Deploy Pages | development

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-shared.yml
    with:
      target_env: development
