name: Deploy Pages | main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: write
    uses: ./.github/workflows/deploy-shared.yml
    with:
      target_env: main
